// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiDeliveryOrderingSystem.Data.Models;

public partial class AnimalType
{
    public int AnimalTypeId { get; set; }

    public string Description { get; set; }

    public virtual ICollection<ShipmentOrderDetail> ShipmentOrderDetails { get; set; } = new List<ShipmentOrderDetail>();
}