// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiDeliveryOrderingSystem.Data.Models;

public partial class HealthCheck
{
    public int HealthCheckId { get; set; }

    public int? ShipmentOrderDetailId { get; set; }

    public int? ShipmentTrackingId { get; set; }

    public DateTime? CheckDate { get; set; }

    public decimal? Weight { get; set; }

    public string Condition { get; set; }

    public decimal? Temperature { get; set; }

    public string DoctorName { get; set; }

    public string Recommendations { get; set; }

    public string PackagingType { get; set; }

    public DateTime? NextCheckupDate { get; set; }

    public virtual ShipmentOrderDetail ShipmentOrderDetail { get; set; }

    public virtual ShipmentTracking ShipmentTracking { get; set; }
}