// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiDeliveryOrderingSystem.Data.Models;

public partial class PackagingProcess
{
    public int PackagingProcessId { get; set; }

    public int? ShipmentOrderId { get; set; }

    public string PackagingType { get; set; }

    public string PackagingInstructions { get; set; }

    public DateTime? PackagingDate { get; set; }

    public string HandlerName { get; set; }

    public string QualityCheckStatus { get; set; }

    public string Remarks { get; set; }

    public DateTime? EstimatedPackagingTime { get; set; }

    public DateTime? ActualPackagingTime { get; set; }

    public decimal? PackagingCost { get; set; }

    public virtual ShipmentOrder ShipmentOrder { get; set; }
}