// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiDeliveryOrderingSystem.Data.Models;

public partial class ShipmentOrderDetail
{
    public int ShipmentOrderDetailId { get; set; }

    public int? ShipmentOrderId { get; set; }

    public int? AnimalTypeId { get; set; }

    public string AdditionalServices { get; set; }

    public decimal? Fee { get; set; }

    public string Status { get; set; }

    public decimal? Weight { get; set; }

    public decimal? Length { get; set; }

    public DateTime? DateOfEntry { get; set; }

    public string Gender { get; set; }

    public string Color { get; set; }

    public string HealthStatus { get; set; }

    public string Age { get; set; }

    public string Achievement { get; set; }

    public string Origin { get; set; }

    public string ImageUrl { get; set; }

    public string Description { get; set; }

    public virtual AnimalType AnimalType { get; set; }

    public virtual ICollection<HealthCheck> HealthChecks { get; set; } = new List<HealthCheck>();

    public virtual ShipmentOrder ShipmentOrder { get; set; }
}