// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiDeliveryOrderingSystem.MVCWebApp.Models;

public partial class Customer
{
    public int CustomerId { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public string Address { get; set; }

    public string MembershipLevel { get; set; }

    public int? TotalOrders { get; set; }

    public double? AverageRating { get; set; }

    public string PreferredShippingMethod { get; set; }

    public string PreferredContactMethod { get; set; }

    public virtual ICollection<ShipmentOrder> ShipmentOrders { get; set; } = new List<ShipmentOrder>();
}